### ISSUE TITLE
build error undefined symbol "cubaworkers_"

### ISSUE THREAD

**Issue by archenemies** [bnaras/cubature#27]
I have been unable to install this package because of the following error:

    Error: package or namespace load failed for ‘cubature’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/home/me/.local/lib64/R/library/00LOCK-cubature/00new/cubature/libs/cubature.so':
      /home/me/.local/lib64/R/library/00LOCK-cubature/00new/cubature/libs/cubature.so: undefined symbol: cubaworkers_
    Error: loading failed
    Execution halted

I am running Arch Linux.

Here is more compiler output:

[cubature.txt](https://github.com/bnaras/cubature/files/4570427/cubature.txt)

Thanks.

**Comment by bnaras** [comment]
Sorry, I don't use Arch Linux.  As the package passes checks on several [Linux platform/toolchain combinations](https://cran.r-project.org/web/checks/check_results_cubature.html), I am inclined to guess the problem lies with your platform/setup/toolchain. If you think otherwise, provide precise details.

**Comment by archenemies** [comment]
Just let me know what commands to run.

By the way sometimes it says "undefined symbol: Cuhre", sometimes it says "undefined symbol: Vegas". It's not just "cubaworkers_" that is undefined.

**Comment by archenemies** [comment]
Does cubature require a recent version of R? I can build it successfully with Arch's R package from April, but not the one I compiled from February. Anyway it looks like the problem is indeed somewhere in my setup, my apologies.

    g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o cubature.so Rcpp-Cuba.o Rcpp-cubature.o RcppExports.o cubature_init.o -Lcubature-1.0.3 -LCuba-4.2 -lcubature -lcuba -L/usr/lib64/R/lib -lR
    installing to /home/frederik/.local/lib64/R/library/00LOCK-cubature/00new/cubature/libs
    ** R
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** installing vignettes
    ** testing if installed package can be loaded from temporary location
    ** checking absolute paths in shared objects and dynamic libraries
    ** testing if installed package can be loaded from final location
    ** testing if installed package keeps a record of temporary installation path
    * DONE (cubature)

**Comment by gnaggnoyil** [comment]
@archenemies Do you still remember which problem you found in your setup then? I've met the similar issue and I would like to know how you solved that in the end.

**Comment by mb706** [comment]
@gnaggnoyil 

I also got this error, sometimes complaining about missing "cubaworkers_", sometimes about missing "cubaverb_". The problem seems to be that there are some implicit dependencies between steps in the Makefile that are not made explicit. I run `make` in concurrent mode (having `MAKEFLAGS` set to `-j <number of CPUs>`) and I get the error.

This used to work for me until a recent system update, it may be that something about `make` or `gcc` changed recently. I would still assume this is a problem with the makefile, and dependencies should be made explicit.

The workaround for me is to run `make` in single-threaded mode, by overwriting `MAKEFLAGS` before running R:
```sh
$ # in bash
$ export MAKEFLAGS="-j 1"
$ R
R version 4.1.3 (2022-03-10) -- "One Push-Up"
Copyright (C) 2022 The R Foundation for Statistical Computing
[....]
Type 'q()' to quit R.

> # now in R
> install.packages("cubature")
```

Installing cubature with many jobs reliably fails with up-to-date fedora 35; it reliably works with the workaround, i.e. `-j` set to 1.

**Comment by genmeblog** [comment]
I've hit this too. If setting MAKEFLAGS doesn't help, check `~/.R/Makevars`.
